# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "2b1b1938ae0241ada9bf46ecf4d31820"
name = "Andrew B app"
application_url = "https://capital-food-katrina-mpeg.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "andrewbaklytsky.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://capital-food-katrina-mpeg.trycloudflare.com/auth/callback",
  "https://capital-food-katrina-mpeg.trycloudflare.com/auth/shopify/callback",
  "https://capital-food-katrina-mpeg.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
